### ISSUE TITLE
List displaying strings does not update correctly

### ISSUE THREAD

**Issue by matthhan** [OutWatch/outwatch#1]
```
import outwatch.dom._
import outwatch.Sink
import scala.scalajs.js.JSApp
import rxscalajs.Observable
object BugList extends JSApp {
  def main():Unit =  {
    //Make an observable that emits two item lists
    val itemLists = Observable.of(
      List("hello","world","!"),
      List("world","!")
    )
    //Make a Sink that prints the items lists to console as they are emitted
    val listsSink = Sink.createSink { lis:List[String] => println(lis) }
    listsSink <-- itemLists
      
    //Map the item lists to lists of html li elements
    val htmlItemLists = itemLists.map{ lis => lis.map { item => li(children := Seq(item)) } } 

    //bind the li elements as children of an ul
    val node = ul(children <-- htmlItemLists)

    OutWatch.render("#app",node)
  }
}
```
This code should intuitively end up displaying a html list that contains the items "world" and "!". However, it actually displays a list containing "hello" and "world". Printing the original lists to the console yields a correct result, so I think this might be a bug in the implementation of the virtual dom?

**Comment by LukaJCB** [comment]
Thank you for adding this issue :) 
I'm not exactly sure what you're trying to do here. Why are you trying to wrap each individual item inside a Seq? Instead of a `li(children := Seq(item))` wouldn't it make more sense, to just have a `li(item)`? 

The underlying problem however, might be that `children` doesn't really work that well with `:=`. I'm considering just removing that feature all together, since you can pass a `Seq` into varargs anyway. 

So in the future instead of writing `li(children := list)` you could only write `li(list: Seq: _*)` to expand the `Seq` to the varargs. 

I'll look into what exactly might be causing this, though and come back to you!

**Comment by matthhan** [comment]
Thanks for your advice. Using the varargs instead of a `Seq` has solved my particular problem. However, I will leave this issue open as you have said that you still want to investigate what the problem with passing it as a `Seq` was.

**Comment by LukaJCB** [comment]
This method is now deprecated in version 0.4.0 :)
