### ISSUE TITLE
Add managed subscription to dom element

### ISSUE THREAD

**Issue by cornerman** [OutWatch/outwatch#121]
How about introducing a new `VDomModifier` that binds a subscription to the lifetime of a dom element:

```scala
case class ManagedSubscription(subscription: IO[Subscription]) extends VDomModifier_
object ManagedSubscription {
  implicit def SubscriptionIsManaged(subscription: IO[Subscription]): VDomModifier = ManagedSubscription(subscription)
}
````

You could use it like this:
```scala
val theSink: Sink[String] = ???
...

val handler = Handler.create[String]
...
div(
  onInput("a") --> handler,
  theSink <-- handler // this would be implicitly converted to a ManagedSubscription
)
```

Now, we could internally register callbacks for dom events and unsubscribe this subscription, when the element is removed from the dom.

Does that make sense?

Maybe we need a more explicit syntax, because it looks very similar to the syntax of `AttributeStreamReceiver`:`div(value <-- handler)`.

**Comment by cornerman** [comment]
Just as simple as?

```scala
def managed(subscription: IO[Subscription]): VDomModifier =
  destroy --> outwatch.Sink.create(_ => subscription.map(_.unsubscribe()))

div( managed(theSink <-- handler) )
```

**Comment by mariusmuja** [comment]
I like the idea, and yes, I think it's as simple. In your example the subscription `IO` doesn't get run (until the node is destroyed), it should be something like this:

```scala
  def managed(subscription: IO[Cancelable]): VDomModifier =
    subscription.flatMap { sub =>
      destroy --> Sink.create(_ => IO(sub.unsubscribe()))
    }

  div( managed(theSink <-- handler) )
```

I added this to the the demo app in `outwatch-extras`, it works as expected:
https://github.com/mariusmuja/outwatch-extras/commit/1186afedd26b0f8bfc4951367d7891932b85d18b

**Comment by cornerman** [comment]
Should we add this to outwatch?

**Comment by mariusmuja** [comment]
I'm in favour of that, I think it's a very useful feature for safely managing subscriptions which otherwise might be left unsubscribed.

 In `outwatch-extras` I added it as a [varargs version and as a single arg version](https://github.com/mariusmuja/outwatch-extras/blob/814a3394c1b88b750bf77c107bca811457deaf13/outwatch-util/src/main/scala/outwatch/extras/package.scala)  for extra efficiency assuming the single arg is the  typical use case. I'be been debating if a varargs version makes sense at all (as it's possible to just include multiple managed modifiers), but I kind of like having all subscriptions to the same handler [in the same place](https://github.com/mariusmuja/outwatch-extras/blob/1186afedd26b0f8bfc4951367d7891932b85d18b/demo-spa/src/main/scala/demo/DemoApp.scala#L208).

**Comment by cornerman** [comment]
I really like the overload with Varargs to write the subscriptions all into one place. I think your solution from outwatch-extras could be used like it is.

**Comment by cornerman** [comment]
Can we do something about `Subscription` that are not IO? For example, this happens, if you just subscribe an observable. So I can use it like this:
```
div( managed(observable(println("debug"))) )
```

Maybe an overload like this:
```
def managed(sub: => Subscription): VDomModifier = managed(IO(sub))
def managed(sub: => Subscription, sub2: => Subscription): VDomModifier = managed(IO(sub), IO(sub2))
```

**Comment by mariusmuja** [comment]
Do you find using:
```
div( managed( IO(observable(println("debug"))) ))
```
too verbose?

**Comment by cornerman** [comment]
meh...you are right.
