### ISSUE TITLE
Replace Observer.onNext with Observer.feed?

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#184]
I'm wondering if it makes sense to use Observer.feed here:

https://github.com/OutWatch/outwatch/blob/68cf2b3723fe539e256fee4258e7cce33c6a5987/src/main/scala/outwatch/Sink.scala#L27

**Comment by cornerman** [comment]
I think both have their use-case. Afaik, `onNext` is fine for emitting a single value, but `feed` is a helper for emitting multiple values while respecting whether the observer stops receiving events.

Maybe, we should just expose the `Observer` interface and not try to replicate the observer interface? Then one can just use the normal monix api.

**Comment by mariusmuja** [comment]
> I think both have their use-case. Afaik, onNext is fine for emitting a single value, but feed is a helper for emitting multiple values while respecting whether the observer stops receiving events.

Even for single values, there's a difference between `onNext` and `feed`. Feed forces an [asynchronous boundary](https://github.com/monix/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/Observer.scala#L193) (necessary to handle back-pressure), while `onNext` does not. This caused an issue in `Store` when emitting synchronous events, for example (fixed in #177).

> Maybe, we should just expose the Observer interface and not try to replicate the observer interface? Then one can just use the normal monix api.

Could be something worth exploring.

**Comment by cornerman** [comment]
Fixed with #203
