### ISSUE TITLE
Building outwatch to the single file

### ISSUE THREAD

**Issue by Twizty** [OutWatch/outwatch#331]
Hello, first of all thank you for a great library, it is finally a pleasure for me to develop frontend! But I have noticed that outwatch generates 3 output files, is there a command to produce single file or should I somhow configure webpack for that?

**Comment by cornerman** [comment]
I am guessing, you are using the outwatch example (https://github.com/OutWatch/seed.g8/blob/master/src/main/g8/build.sbt#L52) or configured something similar in your build.sbt:
```
webpackBundlingMode in fastOptJS := BundlingMode.LibraryOnly() // https://scalacenter.github.io/scalajs-bundler/cookbook.html#performance
```

This will generate 3 files in `fastOptJS`, one file for all your dependencies, one file as a wrapper and entrypoint. And then it generates another file for your actual sources. This way, you do not need to generate everything in webpack when doing `~fastOptJS`.

If you do `fullOptJS`, you should get one js file as output. You should always do full opt for production, because the scala-js compiler will do much optimizations.

Does that help?

**Comment by Twizty** [comment]
Yes, this works, thank you very much.
