### ISSUE TITLE
pull request made it

### ISSUE THREAD

**Issue by elyphas** [OutWatch/outwatch#337]
@fdietze ; Hi, 
I sent a pull request, but doesn't seem to arrive, maybe I doing something wrong.

Sorry, I am learning how to contribute in the OSS.

**Comment by cornerman** [comment]
Hi there,

no worries! No pull request arrived here yet, but let's work on that. You can create a Pull Request via the github UI. Typically if you visit a repository and have a fork with changes, then github will prompt you to create a pull request. Otherwise, you can click on the tab 'Pull requests' and then click the button "New pull request" there (here is a direct link to open a pull request in outwatch against your master branch: https://github.com/OutWatch/outwatch/compare/master...elyphas:master).

In general, it is good practice to create a new branch for a feature in your fork, then open a pull request against that specific feature-branch. It easier to handle multiple branches when not working on master. You can always rebase your feature-branch on master or merge master into your feature-branch to keep it up to date.

**Comment by elyphas** [comment]
Thank you, 

I did it.
