### ISSUE TITLE
Scala 2.13 Example

### ISSUE THREAD

**Issue by sainthasras** [OutWatch/outwatch#390]
Can you please show us how to use outwatch for scala 2.13? Newbies are always around the corner.

**Comment by busti** [comment]
Take a look at the seed project!  https://github.com/OutWatch/seed.g8
It is updated to scala 2.13
You can easily create a new project using this command `sbt new outwatch/seed.g8`.  
It also comes preconfigured with a dev server and hot reloading when you save! Just run the `dev` command in sbt shell.  
If you are on Windows, I'd recomend installing sbt using the chocolatey package manager.  
If you have any further questions, you can always ask on our gitter channel.  

I must apologize for the state of our documentation. There are some architectural changes ( no worries, just the imports will change ) that will be merged soon, that have already been documented properly so I guess nobody feels motivated to update the current docs as that would not last for long.

**Comment by sainthasras** [comment]
Thank you for the swift response and motivation. I will try the instructions and give you feedback.

**Comment by sainthasras** [comment]
I tried using the command **sbt new outwatch/seed.g8** to start a new project. But I get the following error. I am using AdoptOpenJDK 11.

[error] java.io.IOException: Unable to delete file: C:\Users\user\AppData\Local\Temp\giter8-1200787782144267\src\main\g8\.gitignore
[error] Use 'last' for the full log.

**Comment by busti** [comment]
I am not sure about the permissions thing, but as long as the output project looks fine I would not worry.  

Did you perhaps get the following error?  
`java.lang.RuntimeException: /packages cannot be represented as URI`  
If so you need to make sure that you are using java 11. Try running `java -version` to see what java version you are using. There is currently a bug in sbt with java 13.  

Did you get this error instead?  
`java.io.IOException: Cannot run program "yarn"`
In this case you also need to install the program yarn. It is basically the same as `npm`, but is a bit faster and usually more stable. Since you are on windows, I'd recommend installing it using chocolatey: `choco install yarn`.  
During the yarn step when running `sbt dev`, there might be some error messages in the console, but you do not need to worry about those.

**Comment by sainthasras** [comment]
Right. I will try again and post the full logs. Once again, thanks for the reliable and swift response.

**Comment by sainthasras** [comment]
![sample](https://user-images.githubusercontent.com/44950825/75241011-9c428380-57c5-11ea-8c06-c787aef05350.png)


That is the error I get please. And my Java version.

**Comment by cornerman** [comment]
@sainthasras The problem occurs when trying to create a new project from the template `outwatch/seed.g8`. Sadly, there seems to be an issue with `giter8` (the template engine) and windows (see https://github.com/foundweekends/giter8/issues/439 and https://github.com/playframework/play-scala-seed.g8/issues/56).

Can you check whether a new project was actually created in `D:\\outwatchprojects`? Maybe the command still succeeded despite the error.

Otherwise, can you try running `giter8` directly?
```
g8 outwatch/seed.g8
```

**Comment by sainthasras** [comment]
The new project folder was created but when I run sbt dev, it comes up with so many errors. Let me try giter8 directly and see. I don't know how to do that but I will search and try that. Thank you.

**Comment by busti** [comment]
Just in case, I have created a pre-built project here: https://github.com/busti/outwatch-example-preinit  
I created it using giter8 and named the project `owexample`, so whenever that name occurs somewhere you can replace it with yours.

**Comment by sainthasras** [comment]
I have cloned the sample work above. I tried running it and these are the errors: 

![sample2](https://user-images.githubusercontent.com/44950825/75279641-31686b00-580c-11ea-87b2-3523f1a3ea65.png)

**Comment by busti** [comment]
Looks like it cannot find the `git` command. Does typing `git` work in your terminal right now? If not it is missing from the `PATH` environment variable.
Try reinstalling and / or installing git through chocolatey, or try adding it to your `PATH` manually.

**Comment by sainthasras** [comment]
Sure, I did not have git. I installed it using chocolatey. I added it to my PATH manually. I do understand your time for me, but the errors keep coming. Example:

`TypeError: Cannot read property 'document' of undefined
    at $c_Lorg_scalajs_dom_package$.document$lzycompute__p1__Lorg_scalajs_dom_raw_HTMLDocument `

**Comment by busti** [comment]
I tried running the project on a fresh windows installation using git bash. Here's the result:  
![O20k0ZDIH1](https://user-images.githubusercontent.com/3575167/75459048-18cc9200-597f-11ea-88f9-dd61d42f7a46.gif)

From the error it seems like sbt could not load the `scala-js-dom` dependency. Maybe try deleting and cloning the repo again, so you have a fresh install.  

I find it great that you are so persistent. Sorry for the problems during the install. But I believe the lib is worth the efford.

**Comment by busti** [comment]
I will setup a fresh windows tommorrow and try it out there. Maybe there is something missing that I have pre installed on my machine.

**Comment by sainthasras** [comment]
OK. I will be waiting for the update.
And I have to be persistent with you because, you are just one of the few guys out there who have the interest of newbies at heart. On your site, you have step by step instructions that anyone can just follow. What did the rest do?? NOTHING - they don't have time for newbies, only stuff meant for existing users. Yet, they want their frameworks to EXPLODE!!

Please continue the excellent work, and don't forget---- you were also once a newbie!!

**Comment by busti** [comment]
I am sorry but I have to disappoint you. Our VM servers windows image does not work. I cannot get a working windows VM and my laptops SSD is too small to get a working VM there.  

But again, try deleting and re-cloning the repo. Maybe something messed up due to git not being installed.

**Comment by sainthasras** [comment]
That's OK. I am more than grateful for your time. I just hope someday, it works. Thank you Outwatch team.
