### ISSUE TITLE
Make Outwatch FRP-backend agnostic

### ISSUE THREAD

**Issue by fdietze** [OutWatch/outwatch#96]
Different projects already use different FRP/Streaming/State management libraries like `rxjs`, `Monix`, `Xstream`, `scala.rx` or `Diode` to fit their needs.

I think it is time to make Outwatch FRP-backend agnostic to not force the user to use `rxjs`. It would be the first scala-js frontend library to do this (while at the same time extracting the dom-types: #62). If other libraries follow to adopt this flexibility, the eco-system of frontend-libraries becomes more compatible and lowers the barrier to develop better ones.

So how could we provide a solid interface which represents the data-capabilities every UI-Component needs?

My first Idea would be to define two separate type-classes for reading and writing data:

```scala
@typeclass trait Source[+T] {
     def subscribe(onNext: T => Unit):Unit
}

@typeclass trait Sink[-T] {
     def next(value: T): Unit
}
```
(I probably didn't think of every use-case yet, but you get the idea)

The question is if it is even possible to extract an interface which is flexible enough and is still enough to build all existing UI-Libraries upon.

For example: Outwatch internally already uses operators on Observables like `map` and `combineLatest`. What are other libraries using?

What do you think?

@raquo @mariusmuja @LukaJCB @cornerman
(If we think this is possible, we should also invite other frontend library developers to jump in and define a great and flexible interface.)

**Comment by raquo** [comment]
Yep, I'm using `map` / `mapTo` / `filter` / `merge` and maybe some others internally in Laminar. And `unsubscribe` of course.

---

So basically you're proposing to create implementations of such standardized Sink / Source traits in terms of end user's favorite FP library. Then Outwatch or other libraries will be able to use the standardized methods internally, and the end user will be able to use the full gamut of their FP library, right?

This could probably work. Selecting the right set and amount of methods for the standardized traits would be one of the hard parts.

---

Another concern is the small details in subscriptions semantics. For example, xstream.js, my library of choice for now, unsubscribes from streams asynchronously, i.e. the subscription will be gone only after `setTimeout(..., 0)`. Other libraries could be doing it synchronously. That might or might not be a problem, I don't know.

Same goes for how different libraries handle various FRP glitches. Hard for me to say if that would be a problem.

---

Another approach is to define conversions from sinks/sources in library A to sinks/sources in library B, and keep using one library internally in Outwatch, doing the conversion at the edges, so that end users still work with their library of choice. This will be easier for developers and maintainers, but will have a runtime cost of all those conversions.

Cycle.js uses this approach I think. They used to have something similar to what you propose (project "Diversity"), and then changed it in the [Cycle Unified](https://github.com/cyclejs/cyclejs/issues/425) project.

---

There's also a proposal for a standard [EcmaScript Observable](https://github.com/tc39/proposal-observable) type which I believe many JS streaming libraries already support. It should be useful as a foundation, but if I understand correctly it doesn't include any methods like `map` / `filter` / etc.

**Comment by mariusmuja** [comment]
I'll echo what @raquo mentioned above. 

In addition to syntactic differences between different FRP libraries (some provide rich APIs, other more minimal APIs), there's also important semantic differences: some libraries use cold observables by default (that can be transformed into hot observables), some use only hot observables;  there's also differences between how (or if) they handle back-pressure, the threading model used,... Making a single interface to abstract over all these options is going to be hard.

I also think using a single FRP library internally and providing adapters at the edges is a better way of doing it. There is some conversion cost, but I think the cost of abstracting over the semantic differences between different FRP libraries is likely much higher.

In terms of what FRP library to use, my suggestion is [Monix](https://github.com/monix/monix): it's a pure scala FRP library (more typesafe - more better :) ), with a rich API, very efficient, proper back-pressure support and version 3.0 brings deep integration with Cats (on which Outwatch already depends).

I've been using a Monix port of Outwatch for writing some internal tools at my workplace and it's been working great (I actually encountered some issues while using rxjs).

**Comment by raquo** [comment]
Does anyone know how big is Monix in practice, compressed? I mean filesize of monix parts in the JS bundle in fullOpt mode. It's kinda hard to gauge without having a codebase using it properly due to DCE in Scala.js. For comparison, Xstream.js is ~30KB minified, and a bit more is probably added by my Scala interface to it (the parts of it that convert between idiomatic scala and js datatypes, most of everything else should be optimized away in fullOpt mode).

---

I have to agree regarding having a proper Scala API. I had to write a rich interface for xstream to e.g. provide a tuple-based API in place of JS arrays. That was annoooying.

---

On the other hand, I think native Scala libraries are at a disadvantage _in general_ regarding runtime performance. Native JS types should be quite a bit more efficient than JS representations of similar Scala structures. I've seen numbers like 2x performance difference mentioned for equivalent code, but no specific benchmarks handy, sorry.

On the other other hand, I haven't used FRP for DOM manipulation enough to know how much such a performance difference would matter. I feel like it doesn't matter all that much for 99% of events being fired. Exception being animation / scrolling / updating 100500 nodes at once, that kind of thing.

---

Regarding hot and cold observables – Xstream is the odd one here, using only hot observables, whereas most other libraries, while supporting hot (multicast), are cold by default and gravitate towards cold. XStream has a reason for working this way which I think is somewhat similar to our use case. The creator wrote about it quite a bit:

https://staltz.com/why-we-built-xstream.html
https://staltz.com/why-we-actually-built-xstream.html
https://staltz.com/cold-and-hot-callbacks.html

**Comment by raquo** [comment]
Regarding using a featureful vs skinny library consider this: do we want / expect most users to use the internal library we use? If so, it should be featureful for most end users to be happy with it.

On the other hand, if we want / expect most people to use their own preferred library with conversions to our internal library, I'd argue for using as-small-as-possible internal library that is efficient and has the smallest possible footprint, because in that scenario only our own internals care about what that library is, and anything in excess of our internal needs can be considered bloat.

Now, what's a good small library? I don't know, like I said it's hard to tell from a distance due to dead code elimination optimization in Scala.js. Monix might as well be tiny if all we use internally are map/filter/subscribe.

**Comment by mariusmuja** [comment]
It's indeed hard to say what the size of Monix is in a fullOptS bundle because of DCE. Here's for example the size of the Outwatch test bundle:

With RxJS:
```
-rw-rw-r--   1 marius marius  313987 Nov 21 21:41 outwatch-test-opt-bundle.js.gz
-rw-rw-r--   1 marius marius 1593988 Nov 21 21:34 outwatch-test-opt-bundle.js
-rw-rw-r--   1 marius marius  837289 Nov 21 21:33 outwatch-test-opt.js
```
Monix port:
```
-rw-rw-r--   1 marius marius  240514 Nov 21 21:38 outwatch-test-opt-bundle.js.gz
-rw-rw-r--   1 marius marius 1077036 Nov 21 21:38 outwatch-test-opt-bundle.js
-rw-rw-r--   1 marius marius 1046342 Nov 21 21:37 outwatch-test-opt.js
```

In this case it ends up being smaller, but there's not much of the library used in the tests. For real-world applications the situation might be different.

Another reason I like using Monix is that I'm also using it on the server-side, so there's no mental switch when I go from server-side to font-end (and sharing code become easier).

**Comment by fdietze** [comment]
Thank you for your input.

After experimenting, thinking and discussing a lot, I believe that there is a huge difference between event streaming and state management. Even though event streaming can model state to some extent with `scan`, it will never be as powerful for that purpose (Related: #92, https://github.com/monix/monix/issues/467). Let me explain:

If I only manage state in a graph with transformations, I think the only ones I need are `map` and `combineLatest`. When handling only state, operations like `filter` or `fold` do not make much sense, especially in diamond cases. I'm not sure about higher-order cases yet. I can use these assumptions to guarantee *efficient* and *consistent* updates by knowing the whole data flow graph.

In summary:
State Management
* Synchronous
* Every node always has a value
* Knows the whole data flow graph
* Efficient state updates (the minimum amount of calls to the transformation functions)
* Consistent state updates (A node never contains a partial/inconsistent state)
* Only `map` and `combine` operators

Event Streams
* Asynchronous
* Nodes usually don't need to store anything
* Many operators to handler streams in time
* No need to know the whole graph, since only (asynchronous) triggers are involved
* No Data Consistency needed, since Events should be independent
* Can handle simple state (without diamonds) by aggregating with `scan` / `fold`

The bridge between these two concepts are simple:
Event Stream -> aggregation operators like `scan`/`fold` -> State Management
State Management -> update trigger -> Event Stream

The current trend of forcefully unifying these two concepts brings up many limits and trade-offs in my opinion.

So far I think that UI-Components can be rendered by only using state. User interactions emit events.
(Please let me know if you have counter-examples)
Therefore the type-class for `Source` only needs `map` and `combine`. What do you think?

@raquo For what exactly are you using `filter` in laminar?

This insight lead me to fork `scala.rx` and make it a small, powerful state-management library: https://github.com/fdietze/duality

**Comment by raquo** [comment]
@fdietze For Outwatch, Snabbdom provides lifecycle events (update / destroy / remove, etc.). Laminar doesn't use virtual DOM so I had to implement those myself, not only to provide this functionality to end users, but also to properly unsubscribe the listeners when the nodes get unmounted/discarded.

Each Laminar node exposes a stream of mount/unmount events (`$mountEvent`), which is derived from a filtered version of the node's `$parentChangeEvent` – a stream of events that get fired when the node's `maybeParent` is either about to change, or has just changed. The basic idea being if any of the node's ancestors changed from something mounted to something unmounted (or vice versa), we should fire a mount event.

PS this is in `next` branch, not master yet.

**Comment by raquo** [comment]
@fdietze For Outwatch, Snabbdom provides lifecycle events (update / destroy / remove, etc.). Laminar doesn't use virtual DOM so I had to implement those myself, not only to provide this functionality to end users, but also to properly unsubscribe the listeners when the nodes get unmounted/discarded.

Each Laminar node exposes a stream of mount/unmount events (`$mountEvent`), which is derived from a filtered version of the node's `$parentChangeEvent` – a stream of events that get fired when the node's `maybeParent` is either about to change, or has just changed. The basic idea being if any of the node's ancestors changed from something mounted to something unmounted (or vice versa), we should fire a mount event.

PS this is in [`next`](https://github.com/raquo/laminar/blob/next/src/main/scala/com/raquo/laminar/nodes/ReactiveChildNode.scala#L38) branch, not master yet.

**Comment by raquo** [comment]
@fdietze In your state management description, what does "Knows the whole data flow graph" mean, and what's the importance of it?

**Comment by fdietze** [comment]
@raquo When a node knows its predecessors and its successors, changes can be propagated in a controlled way. This is mostly important for the diamond-case (`combineLatest`). With Monix/RxJS the node triggers twice. With scala.rx (which stores the graph information), the node is updated only once, after *all* predecessors calculated their values. There is a description with example in the [scala.rx readme](https://github.com/lihaoyi/scala.rx#basic-usage).

Did this answer your question?

**Comment by raquo** [comment]
@fdietze Yep, thanks! I understand the diamond glitch, I wasn't sure how scala-rx avoided it. Makes sense.

**Comment by fdietze** [comment]
While I think about it, Outwatch triggers multiple times on diamond glitches:
https://github.com/OutWatch/outwatch/blob/master/src/main/scala/outwatch/dom/helpers/DomUtils.scala#L29
This could even lead to visible glitches.

**Comment by mariusmuja** [comment]
There are streaming libraries that reason about the whole graph, for example Akka-Streams: https://doc.akka.io/docs/akka/2.5.4/scala/stream/stream-graphs.html

If having to reason about the whole graph is better or not is debatable, the Monix author argues it's not better:  https://monix.io/docs/2x/reactive/observable-comparisons.html#akka-streams

Personally, I also think it's better to not have to reason about the whole graph, it makes decomposing large applications into mixable components easier. 

Regarding the diamond issue mentioned above, I find that it can be avoided by using a redux-like approach for modeling the components' state. For example:

```scala
import monix.execution.Scheduler.Implicits.global, monix.reactive._, subjects._

val a = PublishSubject[Int]
val c = PublishSubject[Int]

trait Action
case class A(value: Int) extends Action
case class C(value: Int) extends Action

val actions = Observable.merge(a.map(A), c.map(C))

val init = ((0,(0,0)))

val d = actions.scan(init) {
  case (s, A(v)) => s.copy(_1 = v, _2 = s._2.copy(_1 = v))
  case (s, C(v)) => s.copy(_2 = s._2.copy(_2 = v))
}
  .startWith(Seq(init))

val b = d.map(_._2)

d.foreach(println)

a.onNext(1)
```

**Comment by fdietze** [comment]
> There are streaming libraries that reason about the whole graph, for example Akka-Streams: doc.akka.io/docs/akka/2.5.4/scala/stream/stream-graphs.html

> If having to reason about the whole graph is better or not is debatable, the Monix author argues it's not better: monix.io/docs/2x/reactive/observable-comparisons.html#akka-streams

> Personally, I also think not having to reason about the whole graph makes decomposing large applications into mixable components easier.

It's the library which reasons about the graph, not the developer. The data-flow construction and (de)composability is the same for both cases. *Knowing the graph* just means that each node knows its predecessors and successors. Observables only know their successors, which prevents them to avoid glitches in the diamond case.

As you mentioned, the diamond case can be avoided by only having a data flow *tree*, and doing the whole transformation in one single node (Redux/Elm Architecture). Using diamond flows or Redux/Elm is personal preference and depends on the complexity of the application. But this preference is not important for my argument, that diamond cases need to be handled.

The central data node with multiple components attached by definition already produces a diamond case in outwatch, since it uses `combineLatest` internally. Here is a simple example of a non-intuitive, but visible FRP-Glitch:

```scala
val heights = Observable
      .interval(100)
      .zip(Observable.of(0.9, 0.1).repeat(500))
      .map(_._2)

    div(
      div(
        stl("height") <-- heights.map(x => (x * 100) + "px"),
        stl("background-color") := "blue"
      ),
      div(
        stl("height") <-- heights.map(x => ((1-x) * 100) + "px"),
        stl("background-color") := "red"
      )
    )
```
When running this example, the height of the outer `div` first jumps to `20px` or `180px` and then stays at `100px`.

Of course this can be avoided by wrapping *the whole component* in an observable. But if you think this further, it is impractical for whole applications. (If the wrapping is only done where necessary, the developer really has to reason about the data flow graph.)

Even having or preventing these visual glitches is personal preference and depends on the application. This is why I think we should make Outwatch FRP backend-agnostic to let the developer make the best decision for his/her use-case.

The Monix port (which I find great btw!) is a good example for a personal preference of FRP libraries. I prefer something that prevents glitches instead. Using both should be possible.

**Comment by fdietze** [comment]
@mhooo, @cornerman, @LukaJCB and me discussed and started to work on this here:
https://github.com/OutWatch/outwatch/compare/master...fdietze:typeclass
